### PR TITLE
Remove unneccessary keyboard shortcuts

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@fsobolev Do you want to move Toggle Widgets Style down in the list yourself or should I do it?

**Comment by fsobolev** [comment]
You can move it :)

**Comment by ghost** [comment]
Won't that mess up the translations?

**Comment by fsobolev** [comment]
No, filenames and line numbers in `.po` files are for translators, gettext completely ignores them just like any other comments. But I can regenerate files to make it list actual line numbers. If you want, you can try to do this yourself.
After building and running the app, assuming the build dir is `_build` (it's this dir if you use GNOME Builder):
```
cd _build
meson compile cavalier-update-po
```
If you don't have meson installed on the host, you can first enter GNOME Builder sandbox and run commands from there:
```
flatpak run --command=sh org.gnome.Builder
```

**Comment by fsobolev** [comment]
Thank you very much! 😊

**Comment by ghost** [comment]
Thanks for helping me so much!

**Pull request merged**
