### PR TITLE
draw_functions.py: change element height

### LINKED ISSUE #28: Elements get squished in streched window
[Kooha-2023-01-30-11-00-07.webm](https://user-images.githubusercontent.com/119804311/215446477-ecee612c-e825-4146-bf34-6f4020a8f3ae.webm)

In Particles and Levels mode, the elements get thinner the wider the window is. After a certain point in wideness, they start reappearing.

### PR DESCRIPTION
**Pull request by ghost**
Make element height in levels & particles independent of offset, but more dependent on height

This fixed #28 for me.

### CODE REVIEW

**Comment by ghost** [comment]
Known issue: increasing offset makes lower elements go partially off-window.

**Comment by fsobolev** [comment]
I played around a bit with Levels mode and found out that height of elements (`height / 10 - offset_px * 2`) can be less than 1 or even negative when window is stretched. My idea is to limit minimal height to 1 and do the same for width, I'm currently testing this.

**Comment by fsobolev** [comment]
@gregorni I fixed Levels mode, feel free to test. Now I will fix Particles

**Comment by fsobolev** [comment]
@gregorni now everything should be fine

**Comment by ghost** [comment]
@fsobolev Works.

**Comment by fsobolev** [comment]
Sorry I didn't let you fix it yourself, it's just I got an idea how to fix this and it worked 😅 Anyway, thank you :)

**Comment by ghost** [comment]
> Sorry I didn't let you fix it yourself, it's just I got an idea how to fix this and it worked sweat_smile Anyway, thank you :)

No problem, really. I greatly appreciate it when someone finds a way to improve my code.

**Pull request merged**
